### ISSUE TITLE
command 'jumpToSchema' already exists

### ISSUE THREAD

**Issue by alexanderilyin** [redhat-developer/vscode-yaml#1075]
Type: <b>Bug</b>

Start Dev Container

```
Couldn't start client YAML Support
command 'jumpToSchema' already exists
```

Extension version: 1.15.0
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|79.91GB (44.71GB free)|
|Process Argv|--crash-reporter-id 828c2b46-e47b-405a-9312-09a86750d998|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: PartCAD Dev Container @ desktop-linux|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 0)|
|Memory (System)|39.13GB (35.52GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by alexanderilyin** [comment]
Weird, I disabled `redhat.vscode-yaml` in Dev Container but I still have it installed after rebuild container command.

```
[Error - 11:57:31 PM] Server initialization failed.
Error: command 'jumpToSchema' already exists
    at cw.registerCommand (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:31527)
    at Object.registerCommand (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:157:36729)
    at X.register (/home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:382243)
    at X.initialize (/home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:381815)
    at _.initializeFeatures (/home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:402307)
    at /home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:393804
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
[Error - 11:57:31 PM] Starting client failed
Error: command 'jumpToSchema' already exists
    at cw.registerCommand (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:115:31527)
    at Object.registerCommand (file:///vscode/vscode-server/bin/linux-x64/138f619c86f1199955d53b4166bef66ef252935c/out/vs/workbench/api/node/extensionHostProcess.js:157:36729)
    at X.register (/home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:382243)
    at X.initialize (/home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:381815)
    at _.initializeFeatures (/home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:402307)
    at /home/vscode/.vscode-server/extensions/redhat.vscode-yaml-1.15.0/dist/extension.js:2:393804
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
```

Doing rebuild w/o cache now.

**Comment by alexanderilyin** [comment]
How do I ban `redhat.vscode-yaml` for good?
```
⬢ [Docker] ❯ grep redhat.vscode-yaml .devcontainer/devcontainer.json 
        // "redhat.vscode-yaml", # TODO:command 'jumpToSchema' already exists
```

It seems it's still being installed as dependency of other extension?

```
⬢ [Docker] ❯ code --list-extensions | grep yaml
bierner.markdown-yaml-preamble
redhat.vscode-yaml
```

**Comment by jvllmr** [comment]
Uninstalling the codecov plugin fixed this issue for me.
