### ISSUE TITLE
Error: "Couldn't start client Yaml Support"

### ISSUE THREAD

**Issue by aaronkjones** [redhat-developer/vscode-yaml#117]
I am receiving this error. I wiped all of my settings and only installed this plugin.

```
[Error - 11:33:07 AM] Starting client failed
Error: spawn /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```

```
code --version
1.27.2
f46c4c469d6e6d8c46f268d1553c5dc4b475840f
x64
```

**Comment by aaronkjones** [comment]
I apparently didn't wipe out all settings. Reinstalling again fixed.

**Comment by korwalskiy** [comment]
@aaronkjones Could you describe how to go about wiping out all settings. Facing this issue at the moment.

**Comment by JPinkney** [comment]
@korwalskiy Just to make sure, do you have https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml installed and not https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml ? If you do have redhat.vscode-yaml installed can you open a new issue with your os, vscode version, this plugin version etc etc

**Comment by fanttazio** [comment]
I still have this issue:

`[Error - 10:13:57 PM] Starting client failed
Error: spawn /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)`

Code version:
Version 1.35.1 (1.35.1)

Plugin version: 0.4.1

OS: macOS 10.14.5
