### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by neta540** [redhat-developer/vscode-yaml#217]
Running version 0.5.1.

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x56506fc746b6  [/usr/lib/electron4/electron]
 2: 0x56506fc74825  [/usr/lib/electron4/electron]
 3: 0x56506caf6e27  [/usr/lib/electron4/electron]
 4: 0x56506caf6dbb  [/usr/lib/electron4/electron]
 5: 0x56506cb9c943  [/usr/lib/electron4/electron]
 6: 0x56506cb9b77d  [/usr/lib/electron4/electron]
 7: 0x56506cb98df1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/lib/electron4/electron]
 8: 0x56506cba4770  [/usr/lib/electron4/electron]
 9: 0x56506c7861c4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/lib/electron4/electron]
10: 0x56506c96148e  [/usr/lib/electron4/electron]
11: 0x56506cd61b2e  [/usr/lib/electron4/electron]
[Info  - 2:03:33 AM] Connection to server got closed. Server will restart.
[Error - 2:03:33 AM] Request textDocument/formatting failed.
Error: Connection got disposed.
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:71:35)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/main.js:151:15)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at IPCMessageReader.fireClose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 2:03:33 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:71:35)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/main.js:151:15)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at IPCMessageReader.fireClose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 2:03:33 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:71:35)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/main.js:151:15)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at IPCMessageReader.fireClose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 2:03:33 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:71:35)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/main.js:151:15)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at IPCMessageReader.fireClose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 2:03:33 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:71:35)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/main.js:151:15)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at IPCMessageReader.fireClose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 2:03:33 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:71:35)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2153:42)
    at LanguageClient.handleConnectionClosed (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/main.js:151:15)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-languageclient/lib/client.js:2140:18)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at IPCMessageReader.fireClose (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (/home/neta/.vscode-oss/extensions/redhat.vscode-yaml-0.5.1/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.ChildProcess.spawn.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
```

**Comment by JPinkney** [comment]
Can you give some steps to reproduce?

Do you have any schemas associated with the yaml file?

Can you try setting `"yaml.trace.server": "verbose"` in your preferences and then paste the output logs that are found when you select `YAML Support` in the output panel:
![image](https://user-images.githubusercontent.com/8839537/63559707-f1ed5900-c520-11e9-8ed9-bfb5e22fe52e.png)

**Comment by gorkem** [comment]
Closing as it has gone stale.
