### ISSUE TITLE
0.7.1 pre-release is broken

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#268]
I tried to install the 0.7.1 prerelease in vscode-insiders and is mainly broken, also seems to be reporting as version 0.6.1 (probably didn't update internal version)
```
[Trace - 10:08:37 PM] Sending request 'initialize - (0)'.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/Users/ssbarnea/.vscode-insiders/extensions/redhat.vscode-yaml-0.6.1/node_modules/yaml-language-server/out/server/src/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 10:08:37 PM] Connection to server got closed. Server will restart.
[Trace - 10:08:37 PM] Sending request 'initialize - (0)'.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/Users/ssbarnea/.vscode-insiders/extensions/redhat.vscode-yaml-0.6.1/node_modules/yaml-language-server/out/server/src/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 10:08:37 PM] Connection to server got closed. Server will restart.
[Trace - 10:08:37 PM] Sending request 'initialize - (0)'.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/Users/ssbarnea/.vscode-insiders/extensions/redhat.vscode-yaml-0.6.1/node_modules/yaml-language-server/out/server/src/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 10:08:37 PM] Connection to server got closed. Server will restart.
[Trace - 10:08:37 PM] Sending request 'initialize - (0)'.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/Users/ssbarnea/.vscode-insiders/extensions/redhat.vscode-yaml-0.6.1/node_modules/yaml-language-server/out/server/src/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 10:08:37 PM] Connection to server got closed. Server will restart.
[Trace - 10:08:37 PM] Sending request 'initialize - (0)'.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/Users/ssbarnea/.vscode-insiders/extensions/redhat.vscode-yaml-0.6.1/node_modules/yaml-language-server/out/server/src/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 10:08:37 PM] Connection to server got closed. Server will not be restarted.

```

I can assure you that I did uninstall old extension, restarted and confirmed it was uninstalled, before installing the new one.

**Comment by JPinkney** [comment]
Yup, not sure how this happened. I'll re-create the vsix tomorrow morning and repost it.

**Comment by JPinkney** [comment]
@ssbarnea I've just updated the release vsix and re-tested. The new one is now able to start

**Comment by ssbarnea** [comment]
Thanks the new one seems to be working fine but lets not hurry and wait for more feedback. This extension is quite popular and we don't want to risk a bad release.

Also I observed https://github.com/redhat-developer/vscode-yaml/issues/62#issuecomment-578262387 maybe you know a trick.
