### ISSUE TITLE
Yaml Support server crashed 5 times in the last 3 minutes. 

### ISSUE THREAD

**Issue by will-l-h** [redhat-developer/vscode-yaml#52]
I'm getting a prompt at the top of VS Code, "The Yaml Support server crashed 5 times in the last 3 minutes. The server will not be restarted." if my yaml file contains an include, e.g. 

`  customize: !include customize.yaml`

Here's the output from the Yaml Support pane:

Unsupported feature, node kind: 5
C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:78
            valueNode.location = key.value;
                               ^

TypeError: Cannot set property 'location' of undefined
    at recursivelyBuildAst (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:78:32)
    at recursivelyBuildAst (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:64:36)
    at recursivelyBuildAst (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:77:50)
    at recursivelyBuildAst (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:64:36)
    at createJSONDocument (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:153:17)
    at yamlDocs.map.doc (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:179:49)
    at Array.map (native)
    at Object.parse (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\languageService\parser\yamlParser.js:179:38)
    at validateTextDocument (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\server.js:283:37)
    at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (C:\Users\willh\.vscode\extensions\redhat.vscode-yaml-0.0.7\node_modules\yaml-language-server\out\server\src\server.js:275:9)
[Info  - 9:44:15 AM] Connection to server got closed. Server will restart.

**Comment by JPinkney** [comment]
Should be fixed as of our 0.0.8 release!

**Comment by will-l-h** [comment]
Works great, thanks @JPinkney

**Comment by pinnaclesystemsgroup** [comment]
Realize this issue was closed, but I am getting the same error as was reported previously ...



/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 11:31:27 PM] Connection to server got closed. Server will restart.
/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 11:31:28 PM] Connection to server got closed. Server will restart.
/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 11:31:29 PM] Connection to server got closed. Server will restart.
/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 11:31:29 PM] Connection to server got closed. Server will restart.
/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/****/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Error - 11:31:30 PM] Connection to server got closed. Server will not be restarted.

**Comment by odivlad** [comment]
Me too. Sometimes I encounter the `TypeError: Cannot read property 'forEach' of undefined`, and last time I see these errors:
```
enable
/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219
        errors.forEach(e => _doc.errors.push(e));
                                       ^

TypeError: Cannot read property 'push' of undefined
    at errors.forEach.e (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:40)
    at Array.forEach (native)
    at createJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:16)
    at yamlDocs.map.doc (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:53)
    at Array.map (native)
    at Object.parse (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:42)
    at Object.parseYAMLDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:65:59)
    at /Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:232:117
    at Object.get (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/languageModelCache.js:34:33)
    at getJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:240:26)
[Info  - 21:55:22] Connection to server got closed. Server will restart.
enable
/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219
        errors.forEach(e => _doc.errors.push(e));
                                       ^

TypeError: Cannot read property 'push' of undefined
    at errors.forEach.e (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:40)
    at Array.forEach (native)
    at createJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:16)
    at yamlDocs.map.doc (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:53)
    at Array.map (native)
    at Object.parse (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:42)
    at Object.parseYAMLDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:65:59)
    at /Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:232:117
    at Object.get (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/languageModelCache.js:34:33)
    at getJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:240:26)
[Info  - 21:55:23] Connection to server got closed. Server will restart.
enable
/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219
        errors.forEach(e => _doc.errors.push(e));
                                       ^

TypeError: Cannot read property 'push' of undefined
    at errors.forEach.e (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:40)
    at Array.forEach (native)
    at createJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:16)
    at yamlDocs.map.doc (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:53)
    at Array.map (native)
    at Object.parse (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:42)
    at Object.parseYAMLDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:65:59)
    at /Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:232:117
    at Object.get (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/languageModelCache.js:34:33)
    at getJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:240:26)
[Info  - 21:55:23] Connection to server got closed. Server will restart.
enable
/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219
        errors.forEach(e => _doc.errors.push(e));
                                       ^

TypeError: Cannot read property 'push' of undefined
    at errors.forEach.e (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:40)
    at Array.forEach (native)
    at createJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:16)
    at yamlDocs.map.doc (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:53)
    at Array.map (native)
    at Object.parse (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:42)
    at Object.parseYAMLDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:65:59)
    at /Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:232:117
    at Object.get (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/languageModelCache.js:34:33)
    at getJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:240:26)
[Info  - 21:55:24] Connection to server got closed. Server will restart.
enable
/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219
        errors.forEach(e => _doc.errors.push(e));
                                       ^

TypeError: Cannot read property 'push' of undefined
    at errors.forEach.e (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:40)
    at Array.forEach (native)
    at createJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:219:16)
    at yamlDocs.map.doc (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:53)
    at Array.map (native)
    at Object.parse (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/parser/yamlParser.js:255:42)
    at Object.parseYAMLDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:65:59)
    at /Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:232:117
    at Object.get (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/languageModelCache.js:34:33)
    at getJSONDocument (/Users/vlodintsov/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:240:26)
[Error - 21:55:25] Connection to server got closed. Server will not be restarted.
```

Environment:
MacOS: 10.13.3 (17D102)
VSCODE: Version 1.21.0 (1.21.0), 9a199d77c82fcb82f39c68bb33c614af01c111ba

**Comment by armenr** [comment]
I'm getting the same as above, also!

```
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 12:41:12] Connection to server got closed. Server will restart.
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 12:41:13] Connection to server got closed. Server will restart.
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 13:06:59] Connection to server got closed. Server will restart.
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 13:07:00] Connection to server got closed. Server will restart.
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 13:07:00] Connection to server got closed. Server will restart.
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 13:07:01] Connection to server got closed. Server will restart.
/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/armenr/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Error - 13:07:01] Connection to server got closed. Server will not be restarted.
```

**Comment by koliyo** [comment]
I get the same `forEach` error as @armenr

**Comment by efim-a-efim** [comment]
Have this error on Windows too. Log is absolutely similar to @armenr and @odivlad
