### ISSUE TITLE
Memory Leak Detected

### ISSUE THREAD

**Issue by snnsnn** [redhat-developer/vscode-yaml#525]
## Describe the bug

I had following warning in VS Code console output:

```
[0cc] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
```
I traced it to this plugin and confirmed by disabling all other plugins except this one. Here is the console log for the warning:

```
electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
Module.require @ internal/modules/cjs/loader.js:1006
require @ internal/modules/cjs/helpers.js:88
t @ loader.js:1025
r._init @ loader.js:737
r.load @ loader.js:812
r.load @ loader.js:610
l @ loader.js:1631
r._loadModule @ loader.js:1643
r._resolve @ loader.js:1728
r.defineModule @ loader.js:1375
i @ loader.js:1847
E @ bootstrap-window.js:179
async function (async)
E @ bootstrap-window.js:57
(anonymous) @ workbench.js:21
(anonymous) @ workbench.js:216
event.ts:487 [0cc] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:487
_event._event @ event.ts:565
(anonymous) @ event.ts:31
(anonymous) @ event.ts:377
N @ event.ts:377
whenInitialized @ ipc.ts:730
(anonymous) @ ipc.ts:590
w @ async.ts:25
(anonymous) @ ipc.ts:590
requestPromise @ ipc.ts:554
call @ ipc.ts:532
(anonymous) @ ipc.ts:962
Promise.then (async)
call @ ipc.ts:962
log @ telemetryIpc.ts:34
(anonymous) @ telemetryService.ts:140
Promise.then (async)
publicLog @ telemetryService.ts:124
publicLog @ telemetryService.ts:68
publicLog2 @ telemetryService.ts:72
getTreatment @ experimentService.ts:251
async function (async)
getTreatment @ experimentService.ts:213
getStepOverrides @ gettingStartedService.ts:257
(anonymous) @ gettingStartedService.ts:221
(anonymous) @ gettingStartedService.ts:220
_ @ gettingStartedService.ts:212
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
safeCreateInstance @ contributions.ts:121
doInstantiateByPhase @ contributions.ts:95
(anonymous) @ contributions.ts:84
Promise.then (async)
instantiateByPhase @ contributions.ts:84
(anonymous) @ contributions.ts:71
start @ contributions.ts:70
(anonymous) @ workbench.ts:144
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ shared.desktop.main.ts:111
async function (async)
open @ shared.desktop.main.ts:102
w @ desktop.main.ts:40
w.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:190
async function (async)
(anonymous) @ bootstrap-window.js:185
r._invokeFactory @ loader.js:1136
r.complete @ loader.js:1146
r._onModuleComplete @ loader.js:1772
r._onModuleComplete @ loader.js:1784
r._resolve @ loader.js:1732
r.defineModule @ loader.js:1375
p @ loader.js:1822
_ @ loader.js:863
(anonymous) @ tunnelServiceImpl.ts:33
(anonymous) @ fake:1
r._createAndEvalScript @ loader.js:866
(anonymous) @ loader.js:848
v @ loader.js:967
(anonymous) @ loader.js:983
readFileAfterClose @ internal/fs/read_file_context.js:63
event.ts:488     at file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58523
    at file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:61006
    at new Promise (<anonymous>)
    at Object.N [as toPromise] (file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60987)
    at _.whenInitialized (file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4475)
    at file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2720
    at w (file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:11210)
    at file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2710
    at new Promise (<anonymous>)
    at _.requestPromise (file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2252)
    at Object.call (file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:1941)
    at file:///snap/code/65/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:7092
check @ event.ts:488
_event._event @ event.ts:565
(anonymous) @ event.ts:31
(anonymous) @ event.ts:377
N @ event.ts:377
whenInitialized @ ipc.ts:730
(anonymous) @ ipc.ts:590
w @ async.ts:25
(anonymous) @ ipc.ts:590
requestPromise @ ipc.ts:554
call @ ipc.ts:532
(anonymous) @ ipc.ts:962
Promise.then (async)
call @ ipc.ts:962
log @ telemetryIpc.ts:34
(anonymous) @ telemetryService.ts:140
Promise.then (async)
publicLog @ telemetryService.ts:124
publicLog @ telemetryService.ts:68
publicLog2 @ telemetryService.ts:72
getTreatment @ experimentService.ts:251
async function (async)
getTreatment @ experimentService.ts:213
getStepOverrides @ gettingStartedService.ts:257
(anonymous) @ gettingStartedService.ts:221
(anonymous) @ gettingStartedService.ts:220
_ @ gettingStartedService.ts:212
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
safeCreateInstance @ contributions.ts:121
doInstantiateByPhase @ contributions.ts:95
(anonymous) @ contributions.ts:84
Promise.then (async)
instantiateByPhase @ contributions.ts:84
(anonymous) @ contributions.ts:71
start @ contributions.ts:70
(anonymous) @ workbench.ts:144
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ shared.desktop.main.ts:111
async function (async)
open @ shared.desktop.main.ts:102
w @ desktop.main.ts:40
w.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:190
async function (async)
(anonymous) @ bootstrap-window.js:185
r._invokeFactory @ loader.js:1136
r.complete @ loader.js:1146
r._onModuleComplete @ loader.js:1772
r._onModuleComplete @ loader.js:1784
r._resolve @ loader.js:1732
r.defineModule @ loader.js:1375
p @ loader.js:1822
_ @ loader.js:863
(anonymous) @ tunnelServiceImpl.ts:33
(anonymous) @ fake:1
r._createAndEvalScript @ loader.js:866
(anonymous) @ loader.js:848
v @ loader.js:967
(anonymous) @ loader.js:983
readFileAfterClose @ internal/fs/read_file_context.js:63
console.ts:137 [Extension Host] (node:53203) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
_logExtensionHostMessage @ localProcessExtensionHost.ts:514
(anonymous) @ localProcessExtensionHost.ts:282
emit @ events.js:315
emit @ internal/child_process.js:903
processTicksAndRejections @ internal/process/task_queues.js:81
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///snap/code/65/usr/share/code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/USERNAME/.vscode/extensions/redhat.vscode-yaml-0.19.2/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
R @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:246
async function (async)
_getOrCreateGrammarFactory @ abstractTextMateService.ts:235
(anonymous) @ abstractTextMateService.ts:271
_registerDefinitionIfAvailable @ abstractTextMateService.ts:289
(anonymous) @ abstractTextMateService.ts:151
_handle @ extensionsRegistry.ts:141
acceptUsers @ extensionsRegistry.ts:132
_handleExtensionPoint @ abstractExtensionService.ts:785
_doHandleExtensionPoints @ abstractExtensionService.ts:731
_startLocalExtensionHost @ extensionService.ts:465
_scanAndHandleExtensions @ extensionService.ts:435
async function (async)
_scanAndHandleExtensions @ extensionService.ts:346
_initialize @ abstractExtensionService.ts:430
(anonymous) @ extensionService.ts:113
requestIdleCallback (async)
e.runWhenIdle @ async.ts:826
(anonymous) @ extensionService.ts:112
Promise.then (async)
Ga @ extensionService.ts:110
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
get @ instantiationService.ts:54
initLayout @ layout.ts:252
(anonymous) @ workbench.ts:141
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ shared.desktop.main.ts:111
async function (async)
open @ shared.desktop.main.ts:102
w @ desktop.main.ts:40
w.load.configureDeveloperSettings @ workbench.js:32
(anonymous) @ bootstrap-window.js:190
async function (async)
(anonymous) @ bootstrap-window.js:185
r._invokeFactory @ loader.js:1136
r.complete @ loader.js:1146
r._onModuleComplete @ loader.js:1772
r._onModuleComplete @ loader.js:1784
r._resolve @ loader.js:1732
r.defineModule @ loader.js:1375
p @ loader.js:1822
_ @ loader.js:863
(anonymous) @ tunnelServiceImpl.ts:33
(anonymous) @ fake:1
r._createAndEvalScript @ loader.js:866
(anonymous) @ loader.js:848
v @ loader.js:967
(anonymous) @ loader.js:983
readFileAfterClose @ internal/fs/read_file_context.js:63
```

## Steps to Reproduce
1. Install Yaml addon and reload the window.
2. No file is opened.

## Environment
- [ ] Windows
- [ ] Mac
- [ x] Linux
- [ ] other (please specify)

Linux KDE Neon, VS Code version: April 2021 (version 1.56)

**Comment by snnsnn** [comment]
It appears it is something to do with vs code because any active add-on causes this warning.
