### ISSUE TITLE
Cannot read property `id` of undefined with 0.20.0

### ISSUE THREAD

**Issue by jbrudant-decathlon** [redhat-developer/vscode-yaml#537]
## Describe the bug

When the extension is activated, I get the following error message in Developer Tools
> abstractExtensionService.ts:718 Activating extension 'redhat.vscode-yaml' failed: Cannot read property 'id' of undefined.

## Expected Behavior

The extension should be activated.

## Current Behavior

The extension is not activated, hence not usable.

## Steps to Reproduce

Install 0.20.0. I tried with 0.19.2 and everything worked fine.

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
For more info from the extension host:
```
[2021-06-21 11:15:20.224] [exthost] [error] TypeError: Cannot read property 'id' of undefined
	at Object.<anonymous> (/home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/node_modules/@redhat-developer/vscode-redhat-telemetry/lib/vscode/redhatService.js:53:47)
	at Generator.next (<anonymous>)
	at /home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/node_modules/@redhat-developer/vscode-redhat-telemetry/lib/vscode/redhatService.js:27:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/node_modules/@redhat-developer/vscode-redhat-telemetry/lib/vscode/redhatService.js:23:12)
	at Object.getRedHatService (/home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/node_modules/@redhat-developer/vscode-redhat-telemetry/lib/vscode/redhatService.js:52:12)
	at /home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/out/src/extension.js:74:66
	at Generator.next (<anonymous>)
	at /home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/out/src/extension.js:14:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/out/src/extension.js:10:12)
	at activate (/home/jpinkney/.vscode/extensions/redhat.vscode-yaml-0.20.0/out/src/extension.js:72:12)
	at Function._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:13728)
	at Function._callActivate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:13405)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11743
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 0)
```

@fbricon @evidolob Looks like somethings going wrong with the telemetry library (or our intergration with it)

**Comment by evidolob** [comment]
@JPinkney I cannot reproduce that. That trace can be related with vscode version, as telemetry library cannot read `extension.id` from `ExtensionContext` object which we pass from `activate` function.
On which vscode version you tests this?

**Comment by JPinkney** [comment]
I tested on 1.53.2, I just updated to 1.57.1 and everything is working as expected

**Comment by evidolob** [comment]
@JPinkney @fbricon So, maybe, we need to increase minimal supported vscode version?

**Comment by fbricon** [comment]
This is weird, as the telemetry module is built against the [vscode 1.52 API](https://github.com/redhat-developer/vscode-redhat-telemetry/blob/main/package.json#L31),  which definitely defines context.extension

**Comment by fbricon** [comment]
mm actually, it's built against [1.56](https://github.com/redhat-developer/vscode-redhat-telemetry/blob/main/package-lock.json#L433). I'll check what's the actual minimal working requirement

**Comment by fbricon** [comment]
OK so the actual minimum requirement is 1.55

**Comment by fbricon** [comment]
Since Che/Theia is currenty at vscode 1.5.0 AOI level, I'll see if I can change vscode-redhat-telemetry to work in such older environment. If that works, we can replace #540 by a vscode-redhat-telemetry update
