### ISSUE TITLE
Invalid regular expression: Invalid escape on a valid regexp

### ISSUE THREAD

**Issue by kadel** [redhat-developer/vscode-yaml#633]
## Describe the bug

version 1.1.0 of extension throws an error
```
[Error - 9:16:14 AM] SyntaxError: Invalid regular expression: /^([2-9])\.([0-9]+)\.([0-9]+)(\-[0-9a-z-]+(\.[0-9a-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/: Invalid escape
    at new RegExp (<anonymous>)
    at /home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:519760
    at e (/home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:520941)
    at /home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:514102
    at Object.e [as validate] (/home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:516790)
    at h.matchSchemas (/home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:551083)
    at t.YamlCompletion.addPropertyCompletions (/home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:565811)
    at t.YamlCompletion.<anonymous> (/home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:565168)
    at Generator.next (<anonymous>)
    at s (/home/tomas/.vscode/extensions/redhat.vscode-yaml-1.1.0/dist/languageserver.js:2:560319)
```

this is with regexp in the devfile schema https://github.com/devfile/api/blob/937a762988610c2e44620ef266e7f17adaf6eb9e/schemas/latest/devfile.json#L1910

In 1.0.0 this works without any problems

## Expected Behavior
not throw an error

## Current Behavior
throws an error

## Steps to Reproduce
1. add schema for devfile.yaml  to `settings.json`
```
   "yaml.schemas": {
        "https://raw.githubusercontent.com/devfile/api/master/schemas/latest/devfile.json": [
            "devfile.yaml"
        ]
    },
```
2. open devfile.yaml like for example https://github.com/nodeshift-starters/devfile-sample/blob/main/devfile.yaml

## Environment
Linux

**Comment by fbricon** [comment]
@evidolob telemetry shows we get a *ton of these errors since that last release. Please prioritize fixing this ASAP.
