### ISSUE TITLE
'Yaml Support server crashed 5 times in the last 3 minutes' problem in VS Code

### ISSUE THREAD

**Issue by alexpilon666** [redhat-developer/vscode-yaml#66]
Hello,
Having an issue that was already reported, but mine differs somewhat.
After installing the Yaml extension on VS Code for Windows, I keep getting the `The Yaml Support server crashed 5 times in the last 3 minutes. The server will not be restarted` error. After looking in the input, I seem to be missing something:
```
module.js:472
    throw err;
    ^

Error: Cannot find module './languageService/utils/uri'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\apilon\.vscode\extensions\redhat.vscode-yaml-0.0.8\node_modules\yaml-language-server\out\server\src\server.js:13:15)
    at Object.<anonymous> (C:\Users\apilon\.vscode\extensions\redhat.vscode-yaml-0.0.8\node_modules\yaml-language-server\out\server\src\server.js:439:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 13:39:59] Connection to server got closed. Server will not be restarted.
```
What is this module that is missing and/or shouldn't it come with the extension ?

Extension version: 0.0.8
VS Code version: 1.20.0
Windows version: Windows 10 Pro x64 - Fall Creator's Update

Thanks.

**Comment by JPinkney** [comment]
I'm looking into this, I'm not sure if its something that has to do with relative paths in windows or not because I haven't seen it on Fedora or OS X High Sierra

**Comment by robbecker-wf** [comment]
Mine is crashing as well, but for different reasons maybe.
I'm on MacOS 10.13.3 High Sierra.
VS Code 1.20.0
YAML extension 0.0.10

Here's that stack I get 5 times

```
/Users/robbecker/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/robbecker/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/robbecker/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/robbecker/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/robbecker/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/robbecker/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Error - 12:21:58] Connection to server got closed. Server will not be restarted.
```

**Comment by JPinkney** [comment]
@robbecker-wf thats not this extension, thats https://github.com/adamvoss/vscode-yaml

**Comment by robbecker-wf** [comment]
Hah .. you are correct! My bad.

**Comment by JPinkney** [comment]
@alexpilon666 Can you try with the latest version (0.0.9) and let me know if it works

**Comment by alexpilon666** [comment]
@JPinkney Updated to the latest version and it stopped throwing errors!
Thanks a lot for the very quick fix :)
