### ISSUE TITLE
Yaml Support server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by mrkcmo** [redhat-developer/vscode-yaml#69]
Looks like a repeat of an issue from back in 0.8 in VSCode.

```enable
C:\Users\XXX\.vscode\extensions\adamvoss.yaml-0.0.10\server\node_modules\vscode-json-languageservice\lib\services\jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (C:\Users\XXX\.vscode\extensions\adamvoss.yaml-0.0.10\server\node_modules\vscode-json-languageservice\lib\services\jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (C:\Users\XXX\.vscode\extensions\adamvoss.yaml-0.0.10\server\node_modules\vscode-yaml-languageservice\lib\yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (C:\Users\XXX\.vscode\extensions\adamvoss.yaml-0.0.10\server\node_modules\vscode-yaml-languageservice\lib\yamlLanguageService.js:48:62)
    at validateTextDocument (C:\Users\XXX\.vscode\extensions\adamvoss.yaml-0.0.10\server\out\yamlServerMain.js:215:21)
    at Timeout._onTimeout (C:\Users\XXX\.vscode\extensions\adamvoss.yaml-0.0.10\server\out\yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 10:58:14 AM] Connection to server got closed. Server will restart.```

**Comment by JPinkney** [comment]
That isn't an error for this extension. This is an error for github.com/adamvoss/vscode-yaml
