### ISSUE TITLE
The YAML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by cassianoleal** [redhat-developer/vscode-yaml#83]
Lots of people still commenting on https://github.com/redhat-developer/vscode-yaml/issues/52 after it was closed.

I'm also facing the same problem.

```
enable
/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 10:36:46 AM] Connection to server got closed. Server will restart.
enable
/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 10:36:47 AM] Connection to server got closed. Server will restart.
enable
/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 10:36:47 AM] Connection to server got closed. Server will restart.
enable
/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 10:36:48 AM] Connection to server got closed. Server will restart.
enable
/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47
            jsonDocument.syntaxErrors.forEach(addProblem);
                                     ^

TypeError: Cannot read property 'forEach' of undefined
    at JSONValidation.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-json-languageservice/lib/services/jsonValidation.js:47:38)
    at yamlDocument.documents.map.d (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:71)
    at Array.map (native)
    at Object.doValidation (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/node_modules/vscode-yaml-languageservice/lib/yamlLanguageService.js:48:62)
    at validateTextDocument (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:215:21)
    at Timeout._onTimeout (/Users/cassiano/.vscode/extensions/adamvoss.yaml-0.0.10/server/out/yamlServerMain.js:205:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Error - 10:36:49 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by JPinkney** [comment]
This is not this extension. The extension you have installed is https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml. This is the repository for https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml.

**Comment by cassianoleal** [comment]
Argh, you're absolutely correct. I've switched over to this one, and no crashes. Thanks and sorry for the noise!
