### ISSUE TITLE
Extension crashing remote extensions host `Error: ENOENT: no such file or directory, lstat 'tasks'`

### ISSUE THREAD

**Issue by TristanSpeakEasy** [redhat-developer/vscode-yaml#904]
## Describe the bug
`Remote Extension host terminated unexpectedly 3 times within the last 5 minutes`

Caused by:

```
2023-03-15 01:33:04.526 [error] Error: ENOENT: no such file or directory, lstat 'tasks'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
    at /home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:285125
    at f.invoke (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at m.deliver (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at d.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at /home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:98:9669
    at f.invoke (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at m.deliver (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at d.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at m.acceptDocumentsAndEditorsDelta (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:98:13808)
    at m.$acceptDocumentsAndEditorsDelta (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:98:12249)
    at a.N (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
    at a.M (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
    at a.H (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
    at a.G (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:9015)
    at /home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
    at f.invoke (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at m.deliver (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at d.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at p.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
    at /home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
    at f.invoke (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at m.deliver (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at d.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at p.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
    at t.E (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:18973)
    at /home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:16961
    at f.invoke (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at m.deliver (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at d.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at u.acceptChunk (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:12638)
    at /home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:11925
    at f.invoke (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at m.deliver (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at d.fire (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at d.u (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:28911)
    at d.acceptFrame (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:28717)
    at f.l (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:27304)
    at /home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:24627
    at Socket.t (/home/trist/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:22461)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

This is the log from the `Remote Extension Host` output in vscode

Also can occur against other files ie:

```
[error] Error: ENOENT: no such file or directory, lstat '/settings/resourceLanguage'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
```

or 

```
[error] Error: ENOENT: no such file or directory, lstat '/ignoredSettings'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
```

or 

```
[error] Error: ENOENT: no such file or directory, lstat '/workbench-colors'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
```

## Expected Behavior
Don't cause the Remote Extension Host to terminate

## Current Behavior
Remote Extension host terminates

This seemed to only start happening after I updated to the latest version of VSCode: `1.76.1`

## Steps to Reproduce
1. Open VSCode connecting to a WSL2 Ubuntu Container
2. Open any project (with or without YAML files present)
3. Observe VSCode constantly reload extensions until it terminations

## Environment
- [x] Windows
- [ ] Mac
- [ ] Linux
- [x] WSL2 - Ubuntu 20.04

**Comment by TristanSpeakEasy** [comment]
Have downloaded the previous version `1.75.1` and have observed similar errors are still happening ie:

```
[error] Error: ENOENT: no such file or directory, lstat '/home/trist/workspace/writer-client-sdk-python/gen.yaml.git'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
```

and

```
[error] Error: ENOENT: no such file or directory, lstat 'file:///home/trist/.vscode-server/data/logs/20230315T014520/exthost2/exthost.log'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
```

but the Remote Extension Host doesn't terminate so I am able to work without extensions becoming unusable

**Comment by TristanSpeakEasy** [comment]
Okay still seeing the remote extension host crash on the older vscode version but this time it seems to happen on save of a file, instead of immediately on startup.

The last error before remote extension host restarts itself ie before I see logs like `2023-03-15 02:06:07.268 [info] Extension host with pid 3175 started`

is this:

```
2023-03-15 02:05:57.101 [error] Error: ENOENT: no such file or directory, lstat '/home/trist/workspace/openapi-generation/templates/templates/common/common/typeDefs.d.ts.git'
    at Object.lstatSync (node:fs:1516:3)
    at c (/home/trist/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
```

And `/home/trist/workspace/openapi-generation/templates/templates/common/common/typeDefs.d.ts.git` is definitely a file that doesn't exists `typeDefs.d.ts` does but not `typeDefs.d.ts.git`

**Comment by TristanSpeakEasy** [comment]
Just an update I am now not 100% sure it is this extension causing the crashes and I am running through the bisect in vscode to confirm. But the above errors weren't present in version [1.11.0](https://github.com/redhat-developer/vscode-yaml/releases/tag/1.11.0) of this plugin

**Comment by msivasubramaniaan** [comment]
@TristanSpeakEasy The fix will be available on the next release

**Comment by msivasubramaniaan** [comment]
@TristanSpeakEasy Can you please set false on `yaml.recommendations.show` this settings and try it out with v1.12.1?

**Comment by TristanSpeakEasy** [comment]
Disabling that setting does seem to solve the issue on the current version thanks

**Comment by msivasubramaniaan** [comment]
Thanks for the confirmation @TristanSpeakEasy. The actual fix will be available on the next version. Hence close the issue
